# Generated by Django 5.0.4 on 2024-04-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SkinDiseaseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Disease Name")),
                ("definition", models.TextField(verbose_name="Disease Definition")),
                ("reason", models.TextField(verbose_name="Disease Reason")),
                ("solution", models.TextField(verbose_name="Disease Solutions")),
            ],
        ),
    ]
