# Generated by Django 5.0.4 on 2024-04-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skin_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkinDiseasesClassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skin_image", models.ImageField(upload_to="skin_disease/")),
                ("skin_classification", models.CharField(max_length=225)),
                ("skin_accuracy", models.CharField(max_length=225)),
            ],
            options={
                "verbose_name_plural": "Skin Diseases Classification",
            },
        ),
    ]
