# Generated by Django 5.0.4 on 2024-04-26 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("skin_app", "0002_skindiseasesclassification"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SkinDiseasesClassification",
        ),
    ]
